<?php

$router->get('/', function () {
    header('Location: ' . App::url(Auth::check() ? '/dashboard' : '/login'));
    exit;
});
$router->get('/postula', [AdmissionController::class, 'show']);
$router->get('/postula.php', [AdmissionController::class, 'show']);
$router->get('/postula-embed', [AdmissionController::class, 'showEmbed']);
$router->post('/postula', [AdmissionController::class, 'submit']);
$router->post('/postula-embed', [AdmissionController::class, 'submitEmbed']);
$router->post('/webhook/infobip-whatsapp', [InfobipWebhookController::class, 'handle']);
$router->post('/whatsapp/test-template', [WhatsAppController::class, 'testTemplate']);
$router->post('/whatsapp/test-text', [WhatsAppController::class, 'testText']);
$router->post('/whatsapp/admission-confirmation/{id}', [WhatsAppController::class, 'sendAdmissionConfirmation']);
$router->get('/admissions', [AdmissionController::class, 'applications']);
$router->get('/admissions/export', [AdmissionController::class, 'exportApplications']);
$router->post('/admissions/status/{id}', [AdmissionController::class, 'updateApplicationStatus']);
$router->get('/login', [AuthController::class, 'login']);
$router->post('/login', [AuthController::class, 'authenticate']);
$router->get('/logout', [AuthController::class, 'logout']);
$router->get('/dashboard', [DashboardController::class, 'index']);
$router->get('/users', [UserController::class, 'index']);
$router->get('/users/create', [UserController::class, 'create']);
$router->post('/users/store', [UserController::class, 'store']);
$router->get('/users/show/{id}', [UserController::class, 'show']);
$router->get('/users/edit/{id}', [UserController::class, 'edit']);
$router->post('/users/update/{id}', [UserController::class, 'update']);
$router->post('/users/delete/{id}', [UserController::class, 'delete']);
$router->post('/users/status/{id}', [UserController::class, 'status']);
$router->get('/roles', [RoleController::class, 'index']);
$router->get('/roles/create', [RoleController::class, 'create']);
$router->post('/roles/store', [RoleController::class, 'store']);
$router->get('/roles/edit/{id}', [RoleController::class, 'edit']);
$router->post('/roles/update/{id}', [RoleController::class, 'update']);
$router->post('/roles/delete/{id}', [RoleController::class, 'delete']);
$router->get('/admission-courses', [AdmissionCourseController::class, 'index']);
$router->get('/admission-courses/create', [AdmissionCourseController::class, 'create']);
$router->post('/admission-courses/store', [AdmissionCourseController::class, 'store']);
$router->get('/admission-courses/edit/{id}', [AdmissionCourseController::class, 'edit']);
$router->post('/admission-courses/update/{id}', [AdmissionCourseController::class, 'update']);
$router->post('/admission-courses/delete/{id}', [AdmissionCourseController::class, 'delete']);
$router->get('/admission-settings', [AdmissionController::class, 'settings']);
$router->post('/admission-settings', [AdmissionController::class, 'updateSettings']);
$router->get('/mail-settings', [MailSettingsController::class, 'edit']);
$router->post('/mail-settings', [MailSettingsController::class, 'update']);

$router->get('/admission-statuses', [AdmissionStatusController::class, 'index']);
$router->get('/admission-statuses/create', [AdmissionStatusController::class, 'create']);
$router->post('/admission-statuses/store', [AdmissionStatusController::class, 'store']);
$router->get('/admission-statuses/edit/{id}', [AdmissionStatusController::class, 'edit']);
$router->post('/admission-statuses/update/{id}', [AdmissionStatusController::class, 'update']);
$router->post('/admission-statuses/delete/{id}', [AdmissionStatusController::class, 'delete']);
